CREATE DATABASE AUDIODIARY
--> DROP TABLE dbo.[USER]
CREATE TABLE dbo.[USER]		
(
	ID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	[First Name] VARCHAR(50) NOT NULL,
	[Last Name] VARCHAR(50) NOT NULL,
	[Username] VARCHAR(30) UNIQUE NOT NULL,
	[PasswordHash] BINARY(64) NOT NULL
)

--> SELECT ID FROM dbo.[USER] WHERE [Username]='Chibuoyim'

CREATE TABLE dbo.[RECORDINGS]
(
	[ID] INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	[Username] VARCHAR(30) FOREIGN KEY REFERENCES dbo.[USER](Username), 
	[Title] VARCHAR(100) NOT NULL,
	[Mood] VARCHAR(50) NOT NULL,
	[Comments] VARCHAR(200) NOT NULL,
	[Month] INT NOT NULL,
	[Day] INT NOT NULL,
	[Date] INT NOT NULL,
	[Year] INT NOT NULL,
	[URL] VARCHAR(50) NOT NULL
)
-->DROP TABLE dbo.[RECORDINGS]
